

### Tarefa 01

In [102]:
import numpy as np
import pandas as pd

In [103]:
lista_de_centimetros = list(range(170, 190, 5))
lista_de_centimetros

[170, 175, 180, 185]

In [104]:
# Primeiro passo  
array=np.array(lista_de_centimetros)
array

array([170, 175, 180, 185])

In [105]:
# Segundo passo
altura_metro=[]
for n in array:
  transform=n*100
  altura_metro.append(transform)
print(altura_metro)


[17000, 17500, 18000, 18500]


### Tarefa 02


In [106]:
# Primeiro passo
lista_pesos = [70, 75, 80, 85]
lista_array=np.array(lista_pesos)
lista_array

array([70, 75, 80, 85])

In [107]:
lista_array=pd.Series(lista_array)
altura_metro=pd.Series(altura_metro)
consolidado=pd.concat([lista_array,altura_metro],axis=1)
consolidado

0      1
0  70  17000
1  75  17500
2  80  18000
3  85  18500

In [111]:
consolidado.columns=['peso','altura']
df=pd.DataFrame(consolidado)

In [115]:
# Segundo passo
# Tive uma dificuldade nesse passo, ao fazer o laço ele considera o nome da coluna e não o valor 
imc=[]
for peso in consolidado:
  imcc=peso*2
  imc.append(imcc)
print(imc)

['pesopeso', 'alturaaltura']


In [155]:
consolidado.iloc[1]

peso         75
altura    17500
Name: 1, dtype: int64

### Tarefa 03

In [2]:
dados_financeiros=[[3000,1000,6000],[2500,2500,5500],[1000,3000,7000],[10000,5000,16000]]
dados_financeiros=pd.DataFrame(dados_financeiros,columns=['ccusto_fixo','divida_financeira','renda_familiar'])
dados_financeiros

ccusto_fixo  divida_financeira  renda_familiar
0         3000               1000            6000
1         2500               2500            5500
2         1000               3000            7000
3        10000               5000           16000

In [11]:
# Primeira questão
nd_financeiros=np.array(dados_financeiros)
nd_financeiros

array([[ 3000,  1000,  6000],
       [ 2500,  2500,  5500],
       [ 1000,  3000,  7000],
       [10000,  5000, 16000]])

In [30]:
#Segunda questão
isso=nd_financeiros.transpose()
isso

array([[ 3000,  2500,  1000, 10000],
       [ 1000,  2500,  3000,  5000],
       [ 6000,  5500,  7000, 16000]])

In [29]:
# Segunda linha
isso[:][1]

array([1000, 2500, 3000, 5000])

In [63]:
# Segunda coluna
isso[:,1]

array([2500, 2500, 5500])

In [67]:
#Terceira questão
endividamento_total= dados_financeiros['ccusto_fixo']+dados_financeiros['divida_financeira']/dados_financeiros['renda_familiar']
endividamento_total

0     3000.166667
1     2500.454545
2     1000.428571
3    10000.312500
dtype: float64

In [77]:
#Quarta questão
dados_financeiros.iloc[2,2]=10000

novo_endividamento_total= dados_financeiros['ccusto_fixo']+dados_financeiros['divida_financeira']/dados_financeiros['renda_familiar']
novo_endividamento_total


0     3000.166667
1     2500.454545
2     1000.300000
3    10000.312500
dtype: float64

### Tarefa 04

In [78]:
np.random.seed(1234)
poi = np.random.poisson(3, 100)
poi

array([3, 3, 6, 2, 4, 5, 4, 4, 2, 0, 3, 3, 2, 8, 2, 3, 3, 3, 0, 4, 4, 2,
       6, 6, 0, 3, 4, 3, 5, 2, 1, 3, 2, 2, 3, 2, 4, 4, 5, 7, 3, 5, 3, 3,
       2, 2, 3, 6, 2, 2, 4, 3, 5, 2, 5, 3, 0, 2, 1, 1, 4, 4, 4, 6, 2, 4,
       1, 2, 5, 5, 3, 4, 1, 4, 1, 1, 7, 1, 2, 1, 3, 7, 0, 4, 4, 0, 6, 1,
       3, 4, 2, 5, 4, 5, 5, 3, 4, 6, 8, 2])

In [84]:
#Primeira questão
poi==0

array([False, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [97]:
#Segunda questão
verdadeiro = poi==0
verdadeiro.sum()

6

In [99]:
#Terceira questão
poi_nao_zero = poi !=0
poi_nao_zero

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])